### ISSUE TITLE
Speeding up convex decomposition

### ISSUE THREAD

**Issue by grupot3** [sikang/DecompROS#1]
Hi,

One quick question: I've tried _test_path_decomp_3d.cpp_ and it takes ~1305 ms to do the convex decomposition (with the example environment provided).  _test_path_decomp_2d.cpp_  takes 944 ms. 
Is there a way to speed this up? I'd like to achieve runtimes < 10 ms

Thanks a lot!

**Comment by sikang** [comment]
Did you compile it with Release flag? it should not take that long....

**Comment by grupot3** [comment]
Thanks for your quick response. 
My bad, I forgot that flag. Now it's working much faster (17 ms for the 3D example).
If there is any other thing you'd recommend me to make it even faster I'd appreciate it. 

Thanks for your help!

**Comment by sikang** [comment]
No problem:) If you are looking for extremely fast implementation, I think downsample the point cloud will definitely speed up the process, and also the 2D implementation is much faster than 3D.
