### ISSUE TITLE
Computing maximum encompassing ellipsoid

### ISSUE THREAD

**Issue by yash508oza** [sikang/DecompROS#2]
Hi,

Once I obtain the polyhedron using a seed point, is there any support from the library to compute the maximum encompassing ellipsoid lying inside the polyhedron?  

I figured that there is support for generating an ellipsoid around a "path", but what I am looking for is something like this - https://github.com/rdeits/iris-distro

Thanks,
Yash

**Comment by sikang** [comment]
Sorry for the late response, the answer is no -- we used to have it but it got removed, it will be similar to IRIS to compute the max ellipsoid inside the convex hull.

**Comment by yash508oza** [comment]
Cool, thanks for your response!
